#!/usr/bin/env python3
"""Convert the RF.Guru logo into an LVGL RGB565A8 image, for the boot splash.

Run with the PNG as argv[1]; writes components/ui/rfguru_logo.c. Kept as a
script rather than a checked-in blob nobody can regenerate: the source PNG is
at https://rfguru.app/rfguru-logo.png.
"""
import os, subprocess, sys

SIZE = 120


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "rfguru-logo.png"
    raw = subprocess.run(
        ["magick", src, "-resize", f"{SIZE}x{SIZE}", "-background", "none",
         "-gravity", "center", "-extent", f"{SIZE}x{SIZE}", "-depth", "8",
         "RGBA:-"],
        check=True, capture_output=True).stdout
    assert len(raw) == SIZE * SIZE * 4, len(raw)

    rgb565, alpha = bytearray(), bytearray()
    for i in range(SIZE * SIZE):
        r, g, b, a = raw[i * 4:i * 4 + 4]
        v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        rgb565 += bytes((v & 0xFF, v >> 8))      # LVGL stores little-endian
        alpha.append(a)

    body = bytes(rgb565) + bytes(alpha)
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(here, "components", "ui", "rfguru_logo.c")
    with open(out, "w") as f:
        f.write('/* RF.Guru logo, generated by tools/mklogo.py -- do not edit.\n'
                ' * Source: https://rfguru.app/rfguru-logo.png\n'
                ' * Copyright (c) RF.Guru. Used as product branding with\n'
                ' * permission of the project owner.\n */\n'
                '#include "lvgl.h"\n\n'
                'static const uint8_t LOGO[] = {\n')
        for i in range(0, len(body), 16):
            f.write("    " + "".join(f"0x{c:02X}," for c in body[i:i + 16]) + "\n")
        f.write("};\n\n"
                "const lv_image_dsc_t rfguru_logo = {\n"
                "    .header = {\n"
                "        .magic  = LV_IMAGE_HEADER_MAGIC,\n"
                "        .cf     = LV_COLOR_FORMAT_RGB565A8,\n"
                f"        .w      = {SIZE},\n"
                f"        .h      = {SIZE},\n"
                f"        .stride = {SIZE * 2},\n"
                "    },\n"
                f"    .data_size = {len(body)},\n"
                "    .data = LOGO,\n"
                "};\n")
    print(f"{out}: {SIZE}x{SIZE}, {len(body)} bytes of pixel data")


if __name__ == "__main__":
    main()
